---
metadata:
  name: Gbook
  short_name: Gbook
  description: Gbook - awesome GitBook-like documentation for Risk and Acturary
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/GofFavicon32.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/GoFwobg96.png"
  logolink: "/"
  helpUrl: ""
  links:
    - text: Gbook
      link: https://github.com/filipowm/boogi
      external: true
    - text: IFRS
      link: https://www.gatsbyjs.org
      external: true
    - text: References
      link: "/"
      external: false
      submenus:
        - text: GMV
          link: "/"
        - text: GESG
          link: "/"
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/gettingstarted"
      title: ":rocket: Getting Started"
    - order: 2
      path: "/configuration"
      title: ":wrench: Configuration"
    - order: 3
      path: "/editing"
      title: ":writing_hand: Editing Content"
    - order: 4
      path: "/deployment"
      title: ":rocket: Deployment"
    - order: 5
      path: "/developing"
      title: ":computer: Developing"
  links:
    - text: GoF
      link: https://github.com/filipowm/boogi
    - text: React
      link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    trademark:
    name: 
    link: 
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/GofFavicon32.png"

social:
  github: 
  linkedin: 
  twitter: 

features:
  darkMode:
    enabled: true  
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi 
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: false
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
